GET http://localhost:3000/blocks

###

POST http://localhost:3000/blocks
Content-Type: application/json

###

POST http://localhost:3000/peers
Content-Type: application/json

{
    "peer": "ws:localhost:4000"
}

###
GET http://localhost:3000/me/address

###

GET http://localhost:3000/me/balance


###

POST http://localhost:3000/transactions
Content-Type: application/json

{
    "amount": 10,
    "address": "04dd07d35653ae667704edb2e393e8185324353a1c626aad41771e91382c9b953a824bb088979ef11ef55dbaec17b74aed22fedf8a646040733b90f547fd1b6f59"
}

###

GET http://localhost:3000/transactions/
